name = "ElemCo"
uuid = "094d408e-8508-40f4-9646-a254980d91ac"
authors = ["Daniel Kats <d.kats@fkf.mpg.de> and contributors"]
version = "1.0.0-DEV"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GaussianBasis = "9bb1a3dc-0d1c-467e-84f5-0c4ef701360a"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
TensorOperations = ">=3.2.5"
julia = "1.8.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
